### ISSUE TITLE
can't retrieve some dependencies 

### ISSUE THREAD

**Issue by anouarattn** [fastconnect/tibco-bwmaven#1]
Hey 

can't retrieve the following dependencies 
com.tibco.hawk:console:jar:4.9,
 com.tibco.hawk:talon:jar:4.9,
 com.tibco.hawk:util:jar:4.9,
 com.tibco.rv:tibrvj:jar:8.3.
![image](https://cloud.githubusercontent.com/assets/1524123/9660083/c43bbb06-524b-11e5-84ef-9b5c260cb7fd.png)

if I remove them from bw-maven-plugin pom I get the following error
![image](https://cloud.githubusercontent.com/assets/1524123/9660295/cd33dab2-524c-11e5-89ad-c21adb652f51.png)

any help please

**Comment by debovema** [comment]
Hello,

The dependencies you are missing are JARs under licensed of TIBCO that we can't provide.
You have to retrieve these JARs and upload them on your private repository.

Notice: since BWMaven 2.3.2, these dependencies are not required for runtime as they will be automatically provided by using the current configuration. They remain mandatory for compilation-time of course.

Can you retry with the dependencies ? The second error might be related and the stack is too small (important information in Maven are often above the "BUILD FAILURE" message).

Regards,

Mathieu

**Comment by anouarattn** [comment]
It works now

the first problem, I resolve it by copying those jar files into my local repository .m2
the second problem was due to JAVA_HOME pointing to a jre instead of a jdk

thank you

**Comment by debovema** [comment]
Perfect :)
